[package]
name = "boundvariable"
version = "0.1.0"
authors = ["James Wilson <me@unbui.lt>"]
edition = "2018"

[dependencies]
derive_more = "0.13.0"
signal-hook = "0.1.5"

[lib]
name = "common"
path = "src/common/lib.rs"

[profile.release]
lto = true